### ISSUE TITLE
Binningen PLZ

### ISSUE THREAD

**Issue by PmegaOcalc** [creadi/swiss-zipcodes#3]
From https://www.post.ch/de/pages/plz-suche
<img width="1167" alt="screen shot 2018-08-03 at 12 19 41" src="https://user-images.githubusercontent.com/603673/43638029-914fe9d8-9717-11e8-88d1-3450b3cbdc7a.png">
https://github.com/creadi/swiss-zipcodes/blob/master/src/data.ts#L2119
<img width="639" alt="screen shot 2018-08-03 at 12 21 05" src="https://user-images.githubusercontent.com/603673/43638085-c06e3ef4-9717-11e8-8066-0449a3dd87fa.png">
https://raw.githubusercontent.com/TrustChainEG/postal-codes-json-xml-csv/master/data/CH/zipcodes.ch.json

**Comment by cauboy** [comment]
Here's also some resource: http://www.geonames.org/postalcode-search.html?q=&country=CH

**Comment by PmegaOcalc** [comment]
They also have only one 4053 zipcode
<img width="809" alt="screen shot 2018-08-03 at 13 01 10" src="https://user-images.githubusercontent.com/603673/43639690-5ea5ac06-971d-11e8-9e5d-8edf122af760.png">

**Comment by PmegaOcalc** [comment]
https://www.bfs.admin.ch/bfs/en/home/search.html#plz
https://www.bfs.admin.ch/bfsstatic/dam/assets/2861277/master

<img width="441" alt="screen shot 2018-08-03 at 13 36 33" src="https://user-images.githubusercontent.com/603673/43641503-3f6126e8-9724-11e8-87b6-95bce9abc5eb.png">
<img width="392" alt="screen shot 2018-08-03 at 13 37 57" src="https://user-images.githubusercontent.com/603673/43641504-3f7b4988-9724-11e8-8b1b-077c9c3dba58.png">
<img width="438" alt="screen shot 2018-08-03 at 13 39 14" src="https://user-images.githubusercontent.com/603673/43641505-3f97a5a6-9724-11e8-8155-3e0fdc7264ee.png">

The tables list all in the eidg. Building and Housing Registries GWR used 4- and 6-digit postal codes (PLZ4 + PLZZ). The specified percentage (% _in_GDE) indicates the proportion of buildings with the corresponding post code, which is in the listed political community (at 100%, the allocation is accordingly clear).
“the proportion of buildings with the corresponding post code”
4053, 0.52%, Binningen
+
4053, 99.48%, Basel

**Comment by idris-maps** [comment]
Merged missing data from geonames
